In [1]:
import numpy as np

## Транспонирование матрицы

### Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [14]:
A = np.matrix('2 5 7; 9 8 1; 12 11 4; 7 8 5')
print(A)

[[ 2  5  7]
 [ 9  8  1]
 [12 11  4]
 [ 7  8  5]]


In [15]:
print(A.T)

[[ 2  9 12  7]
 [ 5  8 11  8]
 [ 7  1  4  5]]


In [16]:
R = (A.T).T
print(R)

[[ 2  5  7]
 [ 9  8  1]
 [12 11  4]
 [ 7  8  5]]


### Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [17]:
B = np.matrix('1 2 3; 4 5 6; 7 0 8; 9 10 11')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 3 13 19 16]
 [ 7 13 11 18]
 [10  7 12 16]]


In [18]:
print(R)

[[ 3 13 19 16]
 [ 7 13 11 18]
 [10  7 12 16]]


### Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [19]:
A = np.matrix('2 5 7; 9 8 1; 12 11 4')
B = np.matrix('1 2 3; 4 5 6; 7 0 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[ 71  48  84]
 [ 29  58  79]
 [ 92  83 134]]


### Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [20]:
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[ 6 27 36]
 [15 24 33]
 [21  3 12]]


In [21]:
print(R)

[[ 6 27 36]
 [15 24 33]
 [21  3 12]]


### *Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [22]:
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

-57


In [23]:
print(format(A_T_det, '.9g'))

-57


## Умножение матрицы на число

### Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [24]:
L = 1 * A
print(L)

[[ 2  5  7]
 [ 9  8  1]
 [12 11  4]]


In [25]:
print(A)

[[ 2  5  7]
 [ 9  8  1]
 [12 11  4]]


### Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [26]:
Z =np.zeros((3, 3))
L = 0 * A
R = Z
print(L)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
print(R)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [28]:
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[10 25 35]
 [45 40  5]
 [60 55 20]]


In [29]:
print(R)

[[10 25 35]
 [45 40  5]
 [60 55 20]]


### Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [30]:
L = (p * q) * A
R = p * (q * A)
print(L)

[[12 30 42]
 [54 48  6]
 [72 66 24]]


In [31]:
print(R)

[[12 30 42]
 [54 48  6]
 [72 66 24]]


### Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [32]:
L = k * (A + B)
R = k * A + k * B
print(L)

[[ 9 21 30]
 [39 39 21]
 [57 33 36]]


In [33]:
 print(R)

[[ 9 21 30]
 [39 39 21]
 [57 33 36]]


## Сложение матриц

### Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [34]:
L = A + B
R = B + A
print(L)

[[ 3  7 10]
 [13 13  7]
 [19 11 12]]


In [35]:
print(R)

[[ 3  7 10]
 [13 13  7]
 [19 11 12]]


### Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [36]:
C = np.matrix('1 1 1; 2 3 4; 7 2 8')
L = A + (B + C)
R = (A + B) + C
print(L)

[[ 4  8 11]
 [15 16 11]
 [26 13 20]]


In [37]:
print(R)

[[ 4  8 11]
 [15 16 11]
 [26 13 20]]


### Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей

In [38]:
L = A + (-1)*A
print(L)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Умножение матриц

### Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:


In [40]:
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[ 773  342  923]
 [ 745  388  944]
 [1180  589 1472]]


In [41]:
print(R)

[[ 773  342  923]
 [ 745  388  944]
 [1180  589 1472]]


### Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:


In [42]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[132  60 170]
 [ 80  93 132]
 [146 132 222]]


In [43]:
print(R)

[[132  60 170]
 [ 80  93 132]
 [146 132 222]]


###  Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:


In [44]:
L = A.dot(B)
R = B.dot(A)
print(L)

[[ 71  29  92]
 [ 48  58  83]
 [ 84  79 134]]


In [45]:
print(R)

[[ 56  54  21]
 [125 126  57]
 [110 123  81]]


### Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:


In [46]:
E = np.identity(3)
L = E.dot(A)
R = A.dot(E)
print(L)

[[ 2.  5.  7.]
 [ 9.  8.  1.]
 [12. 11.  4.]]


In [47]:
print(R)

[[ 2.  5.  7.]
 [ 9.  8.  1.]
 [12. 11.  4.]]


### Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [48]:
L = Z.dot(A)
R = A.dot(Z)
print(L)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
print(R)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Определитель матрицы

In [54]:
print(np.linalg.det(A))

-57.00000000000001


### Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [52]:
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A_t)

-57.0


### Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [56]:
A = np.matrix('4 1 2; 0 0 0; 3 7 1')
print(A)

[[4 1 2]
 [0 0 0]
 [3 7 1]]


In [58]:
print(np.linalg.det(A))

0.0


## Обратная матрица

In [59]:
b_inv = np.linalg.inv(B)
print(b_inv)

[[-0.88888889  0.35555556  0.06666667]
 [-0.22222222  0.28888889 -0.13333333]
 [ 0.77777778 -0.31111111  0.06666667]]


### Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [60]:
L = np.linalg.inv(B.T)
R = (np.linalg.inv(B)).T
print(L)

[[-0.88888889 -0.22222222  0.77777778]
 [ 0.35555556  0.28888889 -0.31111111]
 [ 0.06666667 -0.13333333  0.06666667]]


In [61]:
print(R)

[[-0.88888889 -0.22222222  0.77777778]
 [ 0.35555556  0.28888889 -0.31111111]
 [ 0.06666667 -0.13333333  0.06666667]]


### Обратная матрица произведения матриц равна произведению обратных матриц:

In [62]:
A = np.matrix('2 5 7; 9 8 1; 12 11 4')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.47368421  1.31851852 -1.14191033]
 [ 0.21052632  0.6962963  -0.57582846]
 [-0.42105263 -1.23703704  1.06276803]]


In [63]:
print(R)

[[ 0.47368421  1.31851852 -1.14191033]
 [ 0.21052632  0.6962963  -0.57582846]
 [-0.42105263 -1.23703704  1.06276803]]


## Ранг матрицы

In [64]:
rank = np.linalg.matrix_rank(A)
print(rank)

3
