## Решение систем линейных уравнений матричным методом 

$$
\left\{\begin{array}\\
    2x_1 - 4x_2 + 3x_3 = 1\\
    x_1 - 2x_2 + 4x_3 = 3\\
    3x_1 - x2 + 5x_3 = 2
    \end{array}
    \right.
$$
    

#### Записываем систему в виде матричного уравнения АX = B, где
#### A - матрица коэффициэнтов
#### Х - матрица неизвестных 
#### B - матрица результатов

In [1]:
import numpy as np

In [4]:
A = np.matrix('2 -4 3; 1 -2 4; 2 -1 5')
B = np.matrix('1; 2; 3')
print(A)

[[ 2 -4  3]
 [ 1 -2  4]
 [ 2 -1  5]]


In [5]:
print(B)

[[1]
 [2]
 [3]]


In [6]:
print(np.linalg.det(A))

-15.0


#### Определитель не равняется 0, следовательно, для этой системы подходит метод решения обратной матрицей

#### Находим обратную матрицу

In [7]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.4        -1.13333333  0.66666667]
 [-0.2        -0.26666667  0.33333333]
 [-0.2         0.4         0.        ]]


#### Решение системы линейных алгебраических уравнений матричным методом определяется по формуле $$ X = A^{-1} * B $$

In [8]:
X = A_inv.dot(B)
print(X)

[[0.13333333]
 [0.26666667]
 [0.6       ]]


In [9]:
print("x1 = ", X[0])

x1 =  [[0.13333333]]


In [10]:
print("x2 = ", X[1])

x2 =  [[0.26666667]]


In [12]:
print("x3 = ", X[2])

x3 =  [[0.6]]


## Решение систем линейных уравнений методом Крамера

#### Теорема Крамера . Если определитель системы отличен от нуля, то система линейных уравнений имеет одно единственное решение, причём неизвестное равно отношению определителей. В знаменателе – определитель системы, а в числителе – определитель, полученный из определителя системы путём замены коэффициентов при этом неизвестном свободными членами. Эта теорема имеет место для системы линейных уравнений любого порядка.

In [16]:
a1 = [2, 1, 2]
a2 = [-4, -2, -1]
a3 = [3, 4, 5]
b = [1, 2, 3]

In [17]:
A = np.transpose(np.matrix([a1, a2, a3]))
print(A)

[[ 2 -4  3]
 [ 1 -2  4]
 [ 2 -1  5]]


In [18]:
B = np.transpose(np.matrix([b]))
print(B)

[[1]
 [2]
 [3]]


#### Определяем вспомогательные матрицы

In [19]:
A1 = np.transpose(np.matrix([b, a2, a3]))
print(A1)

[[ 1 -4  3]
 [ 2 -2  4]
 [ 3 -1  5]]


In [20]:
A2 = np.transpose(np.matrix([a1, b, a3]))
print(A2)

[[2 1 3]
 [1 2 4]
 [2 3 5]]


In [21]:
A3 = np.transpose(np.matrix([a1, a2, b]))
print(A3)

[[ 2 -4  1]
 [ 1 -2  2]
 [ 2 -1  3]]


#### Находим определители главной и вспомогательной матриц

In [24]:
A_det = round(np.linalg.det(A))
A1_det = round(np.linalg.det(A1))
A2_det = round(np.linalg.det(A2))
A3_det = round(np.linalg.det(A3))
print("|A| = ", A_det)
print("|A1| = ", A1_det)
print("|A2| = ", A2_det)
print("|A3| = ", A3_det)

|A| =  -15
|A1| =  -2
|A2| =  -4
|A3| =  -9


In [25]:
x1 = A1_det / A_det
x2 = A2_det / A_det
x3 = A3_det / A_det
print("x = ", x1)
print("y = ", x2)
print("z = ", x3)

x =  0.13333333333333333
y =  0.26666666666666666
z =  0.6
