In [2]:
import numpy as np

### Вектором называется матрица, у которой есть только один столбец или одна строка.

#### Вектор-строка

In [7]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


#### Вектор-столбец

In [3]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


#### Квадратная матрица

In [4]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Диагональная матрица

In [7]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


#### Единичная матрица

In [8]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Нулевая матрица

In [9]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Транспонирование матрицы

In [11]:
A = np.matrix('1 2 3; 4 5 6')
print(A)
print("Транспонированная матрица: \n", A.T)

[[1 2 3]
 [4 5 6]]
Транспонированная матрица: 
 [[1 4]
 [2 5]
 [3 6]]


#### Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [13]:
A = np.matrix('1 2 3; 4 5 6')
print("Исходная матрица\n", A)
R = (A.T).T
print("Дважды транспонированная матрица\n", R)

Исходная матрица
 [[1 2 3]
 [4 5 6]]
Дважды транспонированная матрица
 [[1 2 3]
 [4 5 6]]


#### Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [15]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 8  4]
 [10 12]
 [12 11]]


In [16]:
print(R)

[[ 8  4]
 [10 12]
 [12 11]]


#### Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [17]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[19 43]
 [22 50]]


In [18]:
print(R)

[[19 43]
 [22 50]]


#### Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [19]:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [20]:
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


#### *Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [21]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

-2


In [22]:
print(format(A_T_det, '.9g'))

-2


### Умножение матрицы на число

In [23]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


#### Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [24]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)

[[1 2]
 [3 4]]


In [25]:
print(R)

[[1 2]
 [3 4]]


#### Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [26]:
A = np.matrix('1 2; 3 4')
L = 0 * A
print(L)

[[0 0]
 [0 0]]


#### Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [27]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[ 5 10]
 [15 20]]


In [28]:
print(R)

[[ 5 10]
 [15 20]]


#### Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [29]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)

[[ 6 12]
 [18 24]]


In [31]:
print(R)

[[ 6 12]
 [18 24]]


#### Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [32]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)

[[18 24]
 [30 36]]


In [33]:
print(R)

[[18 24]
 [30 36]]


### Сложение матриц

In [35]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


### Умножение матриц

In [38]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


####  Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:
$$
A * (B + C) = A * B + A * C
$$

In [39]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[35 42]
 [77 94]]


In [40]:
print(R)

[[35 42]
 [77 94]]


### Определитель матрицы

In [41]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [42]:
np.linalg.det(A)

-14.000000000000009

#### Свойства определителя матрицы.

##### Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [43]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [44]:
print(A.T)

[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]


In [45]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)

-14.0


In [46]:
print(det_A_t)

-14.0


##### Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [47]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


In [48]:
np.linalg.det(A)

0.0

#####  Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный.

In [49]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [50]:
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)

[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


In [51]:
round(np.linalg.det(A), 3)

-14.0

In [52]:
round(np.linalg.det(B), 3)

14.0

##### Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю

##### Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [53]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [54]:
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


In [55]:
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k

-28.0

In [56]:
det_B

-28.0

### Обратная матрица

#### Обратной матрицей матрицы называют матрицу, удовлетворяющую следующему равенству:
$$
A * A^{-1} = A^{-1} * A = E
$$

In [57]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


### Ранг матрицы

In [58]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [59]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


#### Если мы приравняем элемент в нижнем правом углу к нулю, то ранг станет равен трем